# Generated by Django 2.2.12 on 2020-09-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品种类')),
            ],
            options={
                'db_table': 'goodsCatalog',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='商品名称')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='进价')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='单价')),
                ('origin_place', models.CharField(max_length=30, verbose_name='产地')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('image_url', models.ImageField(default=None, upload_to='comm_img', verbose_name='图片路径')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('comm_class', models.ForeignKey(on_delete=True, to='goods.GoodsCatalog')),
            ],
            options={
                'db_table': 'goodsInfo',
            },
        ),
    ]
