# Generated by Django 2.2.12 on 2020-09-14 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderinfo',
            fields=[
                ('name', models.CharField(max_length=20, null=True, verbose_name='商品名称')),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='订单号')),
                ('total_count', models.IntegerField(default=1, verbose_name='订单数目')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品总价格')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='运费')),
                ('pay_method', models.SmallIntegerField(default=1, verbose_name='支付方式')),
                ('receiver', models.CharField(default='', max_length=11, verbose_name='收件人')),
                ('address', models.CharField(default='', max_length=100, verbose_name='收货地址')),
                ('receiver_mobile', models.CharField(max_length=11, verbose_name='收件人电话')),
                ('tag', models.CharField(default='', max_length=11, verbose_name='标签')),
                ('status', models.SmallIntegerField(choices=[(1, '待付款'), (2, '待发货'), (3, '待收货'), (4, '已收货')], verbose_name='订单状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
            options={
                'db_table': 'orderInfo',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='购买数量')),
                ('good_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo')),
                ('order_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Orderinfo')),
            ],
            options={
                'db_table': 'orderGoods',
            },
        ),
    ]
